echo "                      ....JggNMMMMMMMMMMMNNNgg...."
echo "                ..+NMMMMMMMMMMM@MMMMMMM@MMMMMMMMMMMMNg.,"
echo "           ..+MMMMB'1MMMMMMMMMM$ HMMMMD MMMMMMMMMMp7THMMMNa,."
echo "        ..MMM#'!   .MMMMMMMMMMM   777^  dMMMMMMMMMMb    ?TMMMNa,"
echo "      .MMM''       ,MMMMMMMMMM#         JMMMMMMMMMMN        ?WMMNJ."
echo "    .MM@!          ,MMMMMMMMMM%          WMMMMMMMMM@           ?MMMe."
echo "  .MMD               MMMMMMMM^            TMMMMMMM@              ,WMN,"
echo " .M#!                 .''''^                ?''''                  ?MMp"
echo ".M#                                                                 JMM;"
echo "dM                                                                   dMN"
echo "MM                                                                   JMM"
echo "HM,                                                                  JM#"
echo ",Mb                                                                 .MM%"
echo " ?Mb                                                               .MMD"
echo "   MN,        .MMMMMNa, .JMMMNJ.        .JMMMN,  .gMMMMMN,        .MM="
echo "    TMm,     .MMMMMMMMMNMMMMMMMMe     .dMMMMMMMNMMMMMMMMMF      .MMD "
echo "      TMN,.   dMMMMMMMMMMMMMMMMMMN,  .MMMMMMMMMMMMMMMMMMM'   .JMM' "
echo "         TMNg..dMMMMMMMMMMMMMMMMMMN,.MMMMMMMMMMMMMMMMMMMl..gMM9^"
echo "            7WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#' "
echo "                ?TWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB'^ "
echo "                       ?''WMMMMMMMMMMMMMMMMMM'''7!"

